export default ({
    DESKTOP: "desktop",
    NOTIFICATION_BUTTON: "notificationButton",
    USER_PREF_MENU: "userPrefMenu",
    HELP_MENU: "helpMenu",
    DATA_BTN: "dataBtn",
    APPS_BTN: "appsBtn",
    ANALYSES_BTN: "analysesBtn",
    TASKBAR: "deTaskBar",
    PREFERENCES_LINK: "preferences",
    COLLABORATORS_LINK: "collaborators",
    TEAMS_LINK: "teams",
    USER_MANUAL_LINK: "userManual",
    INTRO_LINK: "introduction",
    ABOUT_LINK: "about",
    LOGOUT_LINK: "logout",
    SUPPORT_BTN: "support",
    FAQS_LINK: "faqs",
    FORUMS_LINK: "forum",
    FEEDBACK_LINK: "feedback",
    NOTIFICATIONS_MENU: "notificationsMenu",
    EMPTY_NOTIFICATION: "emptyNotification",
    MARK_ALL_SEEN: "markAllSeenLink",
    SEE_ALL_NOTIFICATIONS: "seeAllNotificationsLink",
    RETRY_BTN: "retryBtn",
    NOTIFICATION_LIST: "notificationList",
    NEW_NOTIFICATIONS: "newNotificationsLink",
    NOTIFICATION_MENU_ANCHOR : "notificationMenuAnchor",
    USER_MENU_ANCHOR: "userMenuAnchor",
    HELP_MENU_ANCHOR: "helpMenuAnchor",
});
