export default ({
    desktop: "desktop",
    notificationButton: ".notificationButton",
    userPrefMenu: ".userPrefMenu",
    helpMenu: ".helpMenu",
    dataBtn: ".dataBtn",
    appsBtn: ".appsBtn",
    analysesBtn: ".analysesBtn",
    taskBar: ".deTaskBar",
    preferencesLink: ".preferences",
    collaboratorsLink: ".collaborators",
    sysMsgsLink: ".systemMessages",
    userManualLink: ".userManual",
    introLink: ".introduction",
    aboutLink: ".about",
    logoutLink: ".logout",
    supportBtn: ".support",
    faqsLink: ".faqs",
    forumsLink: ".forum",
    feedbackLink: ".feedback",
});