export default {
    METADATA_TEMPLATE_FORM: "metadataTemplateDialog",

    ATTR_GRID: "attrGrid",
    ATTR_NAME: "name",
    ATTR_DESCRIPTION: "description",
    ATTR_TYPE: "type",
    ATTR_REQUIRED: "required",
    BUTTONS: {
        ADD: "addBtn",
        CLOSE: "closeBtn",
        DELETE: "deleteBtn",
        EDIT: "editBtn",
        EXPAND: "expand",
        MOVE_DOWN: "moveDownBtn",
        MOVE_UP: "moveUpBtn",
        SAVE: "saveBtn",
    },
    CHECK_DELETED: "checkDeleted",
    DIALOG: "dialog",
    ENUM_VALUES_GRID: "enumValuesGrid",
    ENUM_VALUE: "value",
    ENUM_VALUE_DEFAULT: "is_default",
    OLS_PARAMS_EDIT_DIALOG: "olsParamsEditDialog",
    ONTOLOGIES: "ontologies",
    ONTOLOGY_CHILDREN: "children",
    ONTOLOGY_ALL_CHILDREN: "allChildren",
    ONTOLOGY_ENTITY_TYPE: "entityType",
    TEMPLATE_NAME: "templateName",
    TEMPLATE_DESCRIPTION: "description",
    TITLE: "title",
    TITLE_ERR: "errTitle",
};
