export default {
    form: 'searchForm',
    nameHas: 'searchForm.nameHas',
    createdWithin: 'searchForm.createdWithin',
    nameHasNot: ".nameHasNot",
    modifiedWithin: 'searchForm.modifiedWithin',
    metadataAttributeHas: 'searchForm.metadataAttributeHas',
    ownedBy: 'searchForm.ownedBy',
    metadataValueHas: 'searchForm.metadataValueHas',
    sharedWith: 'searchForm.sharedWith',
    fileSizeGreater: 'searchForm.fileSizeGreater',
    fileSizeGreaterUnit: 'searchForm.fileSizeGreaterUnit',
    fileSizeLessThan: 'searchForm.fileSizeLessThan',
    fileSizeLessThanUnit: 'searchForm.fileSizeLessThanUnit',
    includeTrash: 'searchForm.includeTrash',
    searchBtn: 'searchForm.searchBtn',
    filterName: 'searchForm.filterName',
    saveSearchBtn: 'searchForm.saveSearchBtn',
    saveSearchDlg: 'saveSearchDlg',
    saveBtn: 'saveSearchDlg.saveBtn',
    cancelBtn: 'saveSearchDlg.cancelBtn',
    saveTextField: 'saveSearchDlg.input'
};