FROM openjdk:alpine

RUN apk add --update \
    bash \
    git \
    gcc \
    && \
    rm -rf /var/cache/apk/*

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN mkdir -p /root/.gradle && \
    mv sencha_gradle.properties /root/.gradle/gradle.properties

RUN ./gradlew clean

CMD ["./builder.sh"]
