export default {
    CANCEL_BTN: "cancelBtn",
    JOIN_REQUEST_DLG: "joinRequestDlg",
    JOIN_REQUEST_VIEW: ".view",
    APPROVE_BTN: "approveBtn",
    DENY_BTN: "denyBtn",
    SET_PRIVILEGE_DLG: "setPrivilegeDlg",
    OK_BTN: "okBtn",
    TOOLBAR: ".toolbar",
    REFRESH_BTN: "refreshBtn",
    MARK_ALL_SEEN_BTN: "markAllSeenBtn",
    DELETE_BTN: "deleteBtn",
    FILTER: "categoryCbo",
    NOTIFICATION_VIEW: ".notificationView",
    CATEGORY: "categoryColumn",
    MESSAGE: "messageColumn",
    CREATED_DATE: "dateColumn",
    REQUEST_HISTORY_DLG: "requestHistoryDlg",
    DENY_REQUEST_DLG: "denyRequestDlg",
    STATUS: "requestStatusColumn",
    COMMENT: "commentColumn",
};
