export default ({
    NAME: "name",
    OWNER: "owner",
    APP: "app",
    START_DATE: "start_date",
    END_DATE: "end_date",
    STATUS: "status",
    TOOLBAR: "toolbar",
    PARAMETERS: "parameters",
    TYPE:"type",
    VALUE:"value",
    JOB_ID:"jobId",
    ANALYSES_VIEW : ".analysesView",

    MENUITEM_ANALYSES : ".analyses",
    MENUITEM_GO_TO_FOLDER : "goToFolder",
    MENUITEM_VIEW_PARAMS : "viewParams",
    MENUITEM_VIEW_ANALYSES_INFO : "viewInfo",
    MENUITEM_RELAUNCH : "relaunch",
    MENUITEM_DELETE : "delete",
    MENUITEM_CANCEL : "cancel",
    MENUITEM_COMPLETE : ".complete",
    MENUITEM_EDIT : "edit",
    MENUITEM_RENAME : "rename",
    MENUITEM_UPDATE_COMMENTS : "updateComments",
    MENUITEM_SHARE_COLLAB : "sharecollab",
    MENUITEM_SHARE_SUPPORT :"sharesupport",

    VIEW_PARAMS : ".viewParamsView",

    BUTTON_REFRESH : "refresh",

    FIELD_SEARCH : "search",

    ANALYSIS_DOT_MENU : ".dotMenu",
    GRID : ".grid",
    MENUBAR: "menuBar",
    ANALYSIS_NAME_CELL : ".nameCell",
    APP_NAME_CELL : ".appNameCell",
    SUPPORT_CELL : ".supportCell",
    SHARE_WITH_SUPPORT: "shareWithSupport",
    COMMENTS: "comments",

    PERMISSIONS: "permissions",
    APP_TYPE: "appType",
});
