export default {
    BUTTONS: {
        SAVE: "save",
        CANCEL: "cancel",
    },
    ADMIN_DETAILS: {
        NAME: "name",
        DESCRIPTION: "description",
        INTEGRATOR: "integrator",
        INTEGRATOR_EMAIL: "integratorEmail",
        DELETED: "deleted",
        DISABLED: "disabled",
        BETA: "beta",
        WIKI_URL: "wikiURL",
        DOCUMENTATION: "documentation",
        HTCONDOR_EXTRA_REQS: "htcondorExtraReqs",
    },
    DETAILS: {
        APP_INFO: "appInfo",
        APP_TOOLS_TAB: "toolInfoTab",
        APP_TOOLS: "tools",
        APP_DOCUMENTATION_TAB: "appDocTab",
        APP_DOCUMENTATION: "documentation",
        APP_FAVORITE_CELL: "favorite",
        APP_INFO_TAB: "appInfoTab",
        CATEGORIES_TREE: "tree",
        APP_URL_TEXT: ".appUrlText",
        APP_DOC_EDITOR: "docEditor",
        QUICK_LAUNCH: "quickLaunch",
        QUICK_LAUNCH_TAB: "quickLaunchTab",
    },
    QUICK_LAUNCH: {
        name: "name",
        description: "description",
        public: "public",
        create: "createQL",
        cancel: "cancelCreateQL",
        useQuickLaunch: "useQL",
        shareQuickLaunch: "shareQL",
        embedQuickLaunch: "embedQL",
    },
};
