export default {
    TEAMS: {
        TOOLBAR: "toolbar",
        CREATE_BTN: "createBtn",
        TEAM_FILTER: "teamFilter",
        MY_TEAMS_MI: "myTeamsMI",
        ALL_TEAMS_MI: "allTeamsMI",
        SEARCH: "searchField",
    },
    EDIT_TEAM: {
        NAME: "name",
        DESCRIPTION: "description",
        ADMIN: "admin",
        READ: "read",
        VIEW: "view",
        READ_OPT_IN: "readOptin",
        OPT_IN: "optin",
        OPT_OUT: "optout",
        NONE: "none",
        PUBLIC_PRIVILEGES: "publicPrivileges",
        MEMBERS: "members",
        LEAVE_TEAM_DLG: "leaveTeamDlg",
        DELETE_TEAM_DLG: "deleteTeamDlg",
        SEND_JOIN_REQUEST_DLG: "sendJoinRequestDlg",
        SEND_JOIN_REQUEST_MSG: "joinRequestMsg",
        SUBJECT_NAME: "subjectNameCell",
        PRIVILEGE: "privilege",
    },
    BUTTONS: {
        CANCEL: "cancelBtn",
        SAVE: "saveBtn",
        DELETE: "deleteMemberBtn",
        LEAVE_TEAM: "leaveTeamBtn",
        DELETE_TEAM: "deleteTeamBtn",
        JOIN_TEAM: "joinTeamBtn",
        SEND_JOIN_REQUEST: "sendJoinRequestBtn",
    },
};
