export default {
    EDIT_TOOL_DLG: {
        NAME: "name",
        DESCRIPTION: "toolDesc",
        VERSION: "toolVersion",
        ATTRIBUTION: "attribution",
        LOCATION: "location",
        IMAGE_NAME: "imageName",
        DOCKER_URL: "url",
        TYPE: "type",
        OSG_IMAGE_PATH: "osgImagePath",
        ENTRYPOINT: "entrypoint",
        WORKING_DIR: "workingDirectory",
        CONTAINER_UID: "uid",
        MAX_CPU_CORES: "maxCPUCores",
        MEMORY_LIMIT: "memoryLimit",
        MIN_DISK_SPACE: "minDiskSpace",
        CONTAINER_PORTS: "containerPorts",
        PIDS_LIMIT: "pidsLimit",
        RESTRICTED: "restricted",
        NETWORK_MODE: "networkMode",
        TIME_LIMIT: "timeLimit",
        IMPLEMENTOR: "implementor",
        IMPLEMENTOR_EMAIL: "implementorEmail",
        SAMPLE_INPUT_FILES: "sampleInputFiles",
        SAMPLE_OUTPUT_FILES: "sampleOutputFiles",
        CONTAINER_IMAGE: "containerImage",
        TAG: "tag",
        INTERACTIVE: "interactive",
        CONTAINER_NAME: "containerName",
        MIN_MEMORY_LIMIT: "minMemoryLimit",
        CPU_SHARES: "cpuShares",
        MIN_CPU_CORES: "minCPUCores",
        SKIP_TMP_MOUNT: "skipTmpMount",
        CONTAINER_DEVICES: "containerDevices",
        CONTAINER_VOLUMES: "containerVolumes",
        CONTAINER_PORT: "containerPort",
        HOST_PATH: "hostPath",
        CONTAINER_PATH: "containerPath",
        NAME_PREFIX: "namePrefix",
        READ_ONLY: "readOnly",
        TOOL_IMPLEMENTATION: "toolImplementation",
        RESTRICTIONS: "restrictions",
        HOST_PORT: "hostPort",
        BIND_TO_HOST: "bindToHost",
    },
    BUTTONS: {
        SAVE: "saveBtn",
        CANCEL: "cancelBtn",
        ADD: "addBtn",
        DELETE: "deleteBtn",
        EXPAND: "expandBtn",
    },
    PORTS_TABLE: {
        NAME: "name",
        DELETE: "remove",
    },
    DEVICES_TABLE: {
        HOST_PATH: "hostPath",
        CONTAINER_PATH: "containerPath",
    },
};
